# -*- coding: utf-8 -*-
"""Unemployment_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWVlCUrpuTS3NByyl4Jjt9YRK7RE3jlb
"""

## Import and clean the data
import pandas as pd
df =pd.read_csv('/content/API_SL.UEM.TOTL.ZS_DS2_en_csv_v2_115692.csv', skiprows = 4)
df = df.drop(columns=['Indicator Name', 'Indicator Code'])

# Drop any columns that start with 'Unnamed:'
unnamed_cols = [col for col in df.columns if 'Unnamed:' in col]
df = df.drop(columns=unnamed_cols)

# Convert the wide csv format to long format to make it readable for sql.
df_long = pd.melt(
    df,
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="unemployment_rate"
)
# Convert the Year from text to numeric and keep only years from 2000 to match with the inflation analysis.
df_long["year"] = pd.to_numeric(df_long["year"])
df_long = df_long.dropna(subset=["unemployment_rate"])
df_long = df_long[df_long["year"] >= 2000]
df_long = df_long.rename(columns={
    "Country Name": "country_name",
    "Country Code": "country_code"
})
print(df_long.head(10))
print(f"\nTotal rows: {len(df_long)}")

df_long.to_csv('unemployment_clean.csv', index = False)

!pip install pandas sqlalchemy

import pandas as pd
from sqlalchemy import create_engine

# Load the World Bank country CSV - update the path to where your file is
countries = pd.read_csv('/content/Metadata_Country_API_SL.UEM.TOTL.ZS_DS2_en_csv_v2_115692.csv')
print(countries.columns.tolist())
print(countries.head())

# Keep only the columns we need and rename them
countries_clean = countries[['Country Code', 'TableName', 'Region', 'IncomeGroup']].copy()

countries_clean.columns = ['country_code', 'country_name', 'wb_region', 'income_group']

print(countries_clean.shape)
print(countries_clean.head())

from sqlalchemy import create_engine

# Connect to uploaded database
engine = create_engine('sqlite:////content/unemployment_analysis.db')

# Write countries_clean into it
countries_clean.to_sql('countries_lookup', con=engine, if_exists='replace', index=False)

print("Done. Verifying...")

# Verify
verification = pd.read_sql("SELECT COUNT(*) as row_count FROM countries_lookup", engine)
print(verification)

from google.colab import files
files.download('/content/unemployment_analysis.db')

verification = pd.read_sql("SELECT COUNT(*) FROM countries_lookup", engine)
print(verification)